#ROOT=~/svn-margaux/margaux/rcl

LIBLOCK = $(ROOT)/

CFLAGS  += -g -I$(LIBLOCK)
LDFLAGS += -L/usr/local/lib/ -L/usr/lib64/ -L$(ROOT)/liblock -Wl,-rpath=$(realpath $(ROOT)/liblock) -Wl,-rpath=/usr/local/lib -Wl,-rpath=/usr/lib64  -lpapi -lnuma -pthread -rdynamic

Echo=@echo [$(PROJECT)]: 

ifndef VERBOSE
  Verb := @
endif
