CC := gcc
NPROC=$(shell nproc)
CFLAGS := -O3 -pthread -DT$(NPROC) -D_POSIX_C_SOURCE=200112
#CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112
CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels -g
## +EDIT
#LDFLAGS := -lm
## -EDIT

#BASEDIR := ~/svn/margaux/profiling/splash2-base/codes/
ROOT ?= ../../../../..
BASEDIR := $(ROOT)/splash2/splash2-ffwd/codes/
MACROS := $(BASEDIR)/null_macros/c.m4.null
LIB_FFWD = $(ROOT)/libffwd
LDFLAGS := -lm -rdynamic -lpthread -lnuma
NPROC=$(shell nproc)
FFWD_FLAGS := -O3 -g -mcmodel=large -Wall -DT$(NPROC) -DFFWD  -lrt -lnuma -lpthread -I$(LIB_FFWD)

## +EDIT
#M4 := m4 -s -Ulen -Uindex
# We disable synclines because of inaccuracy issues leading several lock declarations to be mapped to the same
# line by addr2line.
M4 := m4 -Ulen -Uindex
## -EDIT

x = *

#$(TARGET): $(OBJS)
#	$(CC) $(OBJS) $(CFLAGS) -o $(TARGET) $(LDFLAGS)


$(TARGET): libffwd.o $(OBJS)
	$(CC) $(BASEDIR)/apps/libffwd.o $(OBJS) $(CFLAGS) $(FFWD_FLAGS) -o $(TARGET) $(LDFLAGS)

clean:
	rm -rf *.o $(BASEDIR)/apps/libffwd.o $(TARGET)

.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) $(MACROS) $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:
	$(CC) -c $(CFLAGS) $(FFWD_FLAGS) $*.c

.C.o:
	$(M4) $(MACROS) $*.C > $*.c
	$(CC) -c $(CFLAGS) $*.c

libffwd.o: $(LIB_FFWD)/libffwd.c
	$(CC) $(FFWD_FLAGS) -c $(LIB_FFWD)/libffwd.c -o $(BASEDIR)/apps/libffwd.o $(LDFLAGS)
